import fs from 'fs';
import path from 'path';

const PROJECT_ROOT = process.cwd();

function cleanup() {
  console.log('🧹 Cleaning up test garbage...');

  // 1. Clean up .opencode/state/guard-mode.log
  const guardLogPath = path.join(PROJECT_ROOT, '.opencode/state/guard-mode.log');
  if (fs.existsSync(guardLogPath)) {
    try {
      fs.unlinkSync(guardLogPath);
      console.log(`  ✅ Removed: ${guardLogPath}`);
    } catch (e) {
      console.error(`  ❌ Failed to remove ${guardLogPath}:`, e);
    }
  }

  // 2. Clean up Windows-style garbage paths in current directory
  // Look for files/dirs starting with \tmp or similar patterns
  try {
    const files = fs.readdirSync(PROJECT_ROOT);
    for (const file of files) {
      // Check for suspicious names generated by path.win32.join on Linux
      if (file.startsWith('\\tmp') || file.includes('omo-sdd-state-')) {
        const fullPath = path.join(PROJECT_ROOT, file);
        try {
          fs.rmSync(fullPath, { recursive: true, force: true });
          console.log(`  ✅ Removed garbage: ${file}`);
        } catch (e) {
          console.error(`  ❌ Failed to remove ${file}:`, e);
        }
      }
    }
  } catch (e) {
    console.error('  ❌ Failed to scan directory for garbage:', e);
  }

  console.log('✨ Cleanup complete.');
}

cleanup();
